spring.application.name=xarvis-gateway
server.port=8088
eureka.client.service-url.defaultZone=http://localhost:8086/eureka
eureka.client.instance.preferIpAddress=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.cloud.gateway.routes[0].id=xarvis-app
spring.cloud.gateway.routes[0].uri=lb://xarvis-app
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/**
spring.cloud.gateway.routes[1].id=xarvis-export
spring.cloud.gateway.routes[1].uri=lb://xarvis-export
spring.cloud.gateway.routes[1].predicates[0]=Path=/ioExport